# Tag-based conditional stages using Cloud Build's built-in $TAG_NAME
# Triggers:
    - Dev:  Event = Push new tag, Tag regex = ^dev-.*$
#   - Prod: Event = Push new tag, Tag regex = ^prod-.*$

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Stage 1"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Stage 1 running..."
        echo "Project: $PROJECT_ID"
        echo "TAG_NAME: ${TAG_NAME:-<none>}"

  # ---------- DEV Stage ----------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "DEV Stage"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        case "${TAG_NAME}" in
          dev-*) 
            echo "Running DEV stage for tag: ${TAG_NAME}"
            # yahan dev ke real actions likho
            ;;
          *)
            echo "Skipping DEV stage... TAG_NAME=${TAG_NAME}"
            exit 0
            ;;
        esac

  # ---------- PROD Stage ----------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "PROD Stage"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        case "${TAG_NAME}" in
          prod-*) 
