substitutions:
  _ENV: "dev"

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Stage 1"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Stage 1 running..."
        echo "_ENV = ${_ENV}"

  # ---------- DEV Stage ----------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "DEV Stage"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$_ENV" = "dev" ]; then
          echo "Running DEV stage..."
        else
          echo "Skipping DEV stage... ENV=${_ENV}"
        fi

  # ---------- PROD Stage ----------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "PROD Stage"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$_ENV" = "prod" ]; then
          echo "Running PROD stage..."
        else
          echo "Skipping PROD stage... ENV=${_ENV}"
        fi

options:
  logging: CLOUD_LOGGING_ONLY
