steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Stage 1"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Stage 1 running..."
        echo "TAG_NAME = ${TAG_NAME:-none}"

  # ---------- DEV Stage ----------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "DEV Stage"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        case "${TAG_NAME}" in
          dev-*)
            echo "Running DEV stage for tag ${TAG_NAME}"
            ;;
          *)
            echo "Skipping DEV stage... TAG_NAME=${TAG_NAME}"
            exit 0
            ;;
        esac

  # ---------- PROD Stage ----------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "PROD Stage"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        case "${TAG_NAME}" in
          prod-*)
            echo "Running PROD stage for tag ${TAG_NAME}"
            ;;
          *)
            echo "Skipping PROD stage... TAG_NAME=${TAG_NAME}"
            exit 0
            ;;
        esac

options:
  logging: CLOUD_LOGGING_ONLY
