steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Cloud Build pipeline triggered successfully!"
        echo "Project ID: $PROJECT_ID"
        echo "Build working directory:"
        ls -lah

options:
  logging: CLOUD_LOGGING_ONLY
