name: Run Python App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ya jo version aap use karte ho

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        run: python main.py  # <-- yaha aap apni file ka naam likho
